### ISSUE TITLE
API v2 is EOL

### ISSUE THREAD

**Issue by ski369fs** [tkrywit/MMM-Solar#10]
API v2 is end of life as of 10/31/2022. Any plans on updating to v4?

**Comment by pnoah** [comment]
Replace -  url: "https://api.enphaseenergy.com/api/v2/systems/",
with -  url: "https://api.enphaseenergy.com/api/v4/systems/",
and it works fine with the new API

**Comment by ski369fs** [comment]
Thank you!!!

**Comment by pnoah** [comment]
I am using v4 of the API. What I had to do is get an access token from my owner account. I requested the token and then was approved. As far as I can tell, this authorization only needs to be done once.   
  
From the developer side, you make the request. You have to amend the request with a return uri, it is cut and paste, then email it to the owner. The owner, in this case me, approved the request and the access token is emailed back to the developer.   
  
I have been accessing v4 for a week now. Unless I am really missing something, it is working fine. The summary return json file is identical to v2.   
  
By the way, I am playing with adding suncalc to provide day and night flags. This way I don’t pull a request at night when nothing is changing and cut into my 1000 monthly limit needlessly. It is only partially working so far.   
  
  
  
 Paul Noah   
  
  
  

  
  
>

**Comment by ski369fs** [comment]
Thanks Paul for the help. Day night flags would be a great addition. I am still trying to get this to work. I was able to successfully get the key and make a connection to the v4 in a browser but for some reason the module just says loading (I confirmed I changed URL to v4 and my config.js file has my apiKey, userId, and systemId). Hopefully I can figure it out as this will be a great addition to my MM.

**Comment by pnoah** [comment]
To share what I did for the day/night test, if you are interested. For the night, here is what I used
https://github.com/mourner/suncalc

I added three new variables to config, lat, lng, and alt; latitude, longitude, and altitude. I added to node_helper.js

var SunCalc = require('./suncalc');

...
			var now=new Date();	
			var times = SunCalc.getTimes(now, payload.config.lat, payload.config.lng, payload.config.alt);			
						
			const hours = (now.getHours() + now.getMinutes()/60.0);
			const sunRise=(times.sunriseEnd.getHours()+times.sunriseEnd.getMinutes()/60.0);  
			const sunSet=(times.sunsetStart.getHours()+times.sunsetStart.getMinutes()/60.0);  
			const isDayTime = ((hours > sunRise) && (hours < sunSet));	
	
			if(isDayTime === true){
 
                          .... existing code  ....

			} else {
				self.sendSocketNotification("NIGHT", 200);
			}	


for the NIGHT socket notification I forced current power to 0 and updated status to Night instead of Normal.

I did one other change, I added this for the initial call when the module first starts.  It was easier than adding new logic.

		if(notification === "GET_INITIALSOLAR") {
			var enlightenUrl = payload.config.url + payload.config.systemId + "/summary?&key=" + payload.config.apiKey + "&user_id=" + payload.config.userId;
			Log.log("Getting Solar Data");
			console.log(enlightenUrl);
			request(enlightenUrl, function (error, response, body) {
			if (!error && response.statusCode == 200) {
				var jsonData = JSON.parse(body);
					self.sendSocketNotification("SOLAR_DATA", jsonData);
				}
			});
			//self.sendSocketNotification("SOLAR_DATA", 200);
		}

hope this helps.

Paul

**Comment by ski369fs** [comment]
Thanks Paul, that looks great. Unfortunately , I still can't get the basic Model to work. I see it starts up and it keeps trying to grab data (console shows "SolarApp: getting data") but nothing updates. Model just says "Loading...". Any ideas? Some of your code is a bit different than mine (I don't have "GET_INITIALSOLAR"). Any chance you can send me a zip of your modal (minus api credentials). Anything help would be super appreciated. 
Thanks again
Yoni

**Comment by pnoah** [comment]
Sure.  All my information is in config.js which I don't include.  On thing to try is I print out the url to the enphase web site and you copy it and try that in a browser and see if you get errors.  

The suncalc code in included as a folder

I called it ENSolar just so I had a working version different from the original.

The GET_INITIALSOLAR is just the code without the day/night test.  First time it runs, I don't want to not get the data.



[MMM-ENSolar.zip](https://github.com/tkrywit/MMM-Solar/files/10405146/MMM-ENSolar.zip)

**Comment by ski369fs** [comment]
Thanks for sending, gave me suggestions for when I finally get it working. I am able to confirm the URL does work when I put in a browser, just seems to not work in the model. Unfortunately, I wasn't able to find anything different in your code that points me in the right direction. Hopefully I will be able to get it working at some point. 

Thanks again

**Comment by monty124** [comment]
rather than create a new issue, i thought i'd update here on what i have found
v2 EOL has been extended to March 31, 2023 (https://developer-v4.enphase.com/aboutproduct.html) after that they mention it will be decommissioned but who knows, it also says 2 versions of the api are maintained at all times.
The current code 100% will not work with v4 there are different auth mechanisms as you can see here for v4 and the code does not support this 
https://developer-v4.enphase.com/docs/quickstart.html, take note at Authentication and Authorization flow for a developer application

with respect to the loading issue mentioned in #3 this may be due to not performing the final application authority using the url in the dev console when you create your api key (poor doco here maybe)

I may try and take a look at this and get working with v4 and improve the documentation with a fork and pr but i am not real good at javascript (well i have no idea tbh) but also time permitting

as it stands it is working on v2 when you satisfy all the requirements on the enphase side; but i expect it will be short lived

**Comment by ski369fs** [comment]
Thanks, for some reason I was not able to get it to work. But since we are moving in a few months I won't be spending anymore time on it. Glad it is still working for you. Thanks again for your help.
